### ISSUE TITLE
Add the files for task 4 in Week_4

### ISSUE THREAD

**Issue by madoils** [madoils/Jailbreaker_capitals_groupwork#20]

**Comment by zamperin** [comment]
completed in https://github.com/madoils/Jailbreaker_capitals_groupwork/commit/6fdef6f0b8e8c46034ca2a07d6c8d2adf02a4d02 and modified the readme in https://github.com/madoils/Jailbreaker_capitals_groupwork/commit/85d6a5655d5501bef6a9dd3714149106421b1f64
